name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 5'

env:
  COOKIE: 'ATVNqfLH9EAdrZGpzH5KSedbV0mM00ZPuYIvvb8d+YLOu4xPuynh3/8cmhn+bNPsSRyOsjM5eTPbCuDvv4so30O4b85IqYLbxb7St1B2evYAszI0h0YsEqz4b0aDVW69M2NCriV44/HC6wTcVs7gK2GR7qdvvJXfixr9UxUyGBpThUpVLCVSa8i3LMUpvS7CXbWhg1rWmttDRfTENQ63U0rIQ3lJeafoXKWBeXRABby07wBbx0x+Wc2iNcIwaJR9VA=='

jobs:
  check-for-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python update.py